Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -31,9 +31,14 @@ jobs:
       run: |
         docker build -t akanshachauhary/node-app .
 
+    - name: Log in to Docker Hub
+      uses: docker/login-action@v2  # Using the official Docker login action
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
+
     - name: Push Docker image to Docker Hub
       run: |
-        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
         docker push akanshachauhary/node-app:latest
 
   deploy:
@@ -53,5 +58,5 @@ jobs:
           docker pull akanshachauhary/node-app:latest
           docker stop my-node-app || true
           docker rm my-node-app || true
-          docker run -d -p 80:3000 --name node-app akanshachauhary/node-app:latest
-
+          docker run -d -p 80:3000 --name node-app akanshachauhary/node-app:latest || exit 1
+          docker system prune -af || true  # Clean up unused Docker images and containers
